### ISSUE TITLE
请问Cookie-Editor在通义千问的页面 not have any cookies.该如何做？

### ISSUE THREAD

**Issue by lemon-little** [leeeduke/revTongYi#1]
<img width="1029" alt="image" src="https://github.com/leeeduke/revTongYi/assets/53484050/b92aacec-612a-4fce-9b0a-5cde8e28e8e5">

**Comment by lemon-little** [comment]
现在可以了，打扰了

**Comment by myt2000** [comment]
@lemon-little 怎么解决的，我也是获取不到

**Comment by leeeduke** [comment]
> @lemon-little 怎么解决的，我也是获取不到

可以刷新然后试试
