### ISSUE TITLE
错误的 sessionId 判断

### ISSUE THREAD

**Issue by leeeduke** [leeeduke/revTongYi#12]
https://github.com/leeeduke/revTongYi/blob/8595f71e46797a51e4213838f2b1036ae3961a2a/revTongYi/qianwen.py#L124

当用户传递 `sessionId = ""` 以开启新对话时，仍然会使用 self.sessionId

**Comment by old-dream321** [comment]
问题是cli又要用这个，所以我的建议是直接取消self.sessionId，cli用的时候自己保存一个

**Comment by leeeduke** [comment]
可以

**Comment by old-dream321** [comment]
已解决，你看没问题的话发release吧

**Comment by old-dream321** [comment]
@leeeduke

**Comment by leeeduke** [comment]
ok了
